# Generated by Django 2.1b1 on 2018-06-25 13:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Callsign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(max_length=8)),
                ('type', models.CharField(blank=True, choices=[('personal', 'Personal'), ('club', 'Club'), ('repeater', 'Repeater'), ('beacon', 'Beacon'), ('educational', 'Educational'), ('experimental', 'Experimental'), ('special_event', 'Special Event'), ('shortwave_listener', 'Shortwave Listener')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('issued', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('callsign', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callsign.Callsign')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClublogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('first_qso', models.DateTimeField()),
                ('last_qso', models.DateTimeField()),
                ('last_upload', models.DateTimeField()),
                ('oqrs', models.BooleanField()),
                ('callsign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.Callsign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('adif', models.PositiveSmallIntegerField(db_index=True)),
                ('cq_zone', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)], verbose_name='CQ zone')),
                ('itu_zone', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(75)], verbose_name='ITU zone')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('continent', models.CharField(choices=[('AF', 'Asia'), ('AN', 'Antarctica'), ('AS', 'Africa'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2)),
                ('utc_offset', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(-12), django.core.validators.MaxValueValidator(15)], verbose_name='UTC offset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DMRID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.PositiveSmallIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('callsign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callsign.Callsign')),
            ],
            options={
                'verbose_name': 'DMR ID',
            },
        ),
        migrations.CreateModel(
            name='ESQLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('callsign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.Callsign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LOTWUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('last_activity', models.DateTimeField()),
                ('callsign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.Callsign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='callsign',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='callsign.Country'),
        ),
        migrations.AddField(
            model_name='callsign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
