# Generated by Django 2.1 on 2018-12-28 15:07

import callsign.utils
from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        CreateExtension('postgis'),
        migrations.CreateModel(
            name='CallSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', callsign.utils.CallSignField(db_index=True, max_length=16, unique=True)),
                ('cq_zone', callsign.utils.CQZoneField(blank=True, null=True, verbose_name='CQ zone')),
                ('itu_zone', callsign.utils.ITUZoneField(blank=True, null=True, verbose_name='ITU zone')),
                ('itu_region', callsign.utils.ITURegionField(blank=True, null=True, verbose_name='ITU region')),
                ('grid', callsign.utils.QTHLocatorField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('type', models.CharField(blank=True, choices=[('beacon', 'Beacon'), ('club', 'Club'), ('educational', 'Educational'), ('experimental', 'Experimental'), ('military', 'Military'), ('personal', 'Personal'), ('repeater', 'Repeater'), ('shortwave_listener', 'Shortwave Listener'), ('special_event', 'Special Event')], max_length=32)),
                ('active', models.BooleanField(default=True)),
                ('issued', models.DateField(blank=True, null=True)),
                ('dstar', models.BooleanField(default=False, verbose_name='D-STAR')),
                ('comment', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CallSignPrefix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(db_index=True, max_length=16, unique=True)),
                ('cq_zone', callsign.utils.CQZoneField(blank=True, null=True)),
                ('itu_zone', callsign.utils.ITUZoneField(blank=True, null=True)),
                ('itu_region', callsign.utils.ITURegionField(blank=True, null=True)),
                ('continent', models.CharField(blank=True, choices=[('AF', 'Asia'), ('AN', 'Antarctica'), ('AS', 'Africa'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], max_length=2)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('utc_offset', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('beacon', 'Beacon'), ('club', 'Club'), ('educational', 'Educational'), ('experimental', 'Experimental'), ('military', 'Military'), ('personal', 'Personal'), ('repeater', 'Repeater'), ('shortwave_listener', 'Shortwave Listener'), ('special_event', 'Special Event')], max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('callsign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callsign.CallSign')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClublogUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('clublog_first_qso', models.DateTimeField()),
                ('clublog_last_qso', models.DateTimeField()),
                ('clublog_last_upload', models.DateTimeField()),
                ('clublog_oqrs', models.BooleanField()),
                ('callsign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.CallSign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('adif_name', models.CharField(blank=True, db_index=True, max_length=64)),
                ('alpha_2', models.CharField(db_index=True, max_length=2, unique=True)),
                ('alpha_3', models.CharField(db_index=True, max_length=3, unique=True)),
                ('numeric_3', models.CharField(db_index=True, max_length=3, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DMRID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.PositiveIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('callsign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmr_ids', to='callsign.CallSign')),
            ],
            options={
                'verbose_name': 'DMR ID',
            },
        ),
        migrations.CreateModel(
            name='DXCCEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('deleted', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='callsign.Country')),
            ],
            options={
                'verbose_name': 'DXCC Entry',
                'verbose_name_plural': 'DXCC Entries',
            },
        ),
        migrations.CreateModel(
            name='EQSLUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('callsign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.CallSign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LOTWUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('lotw_last_activity', models.DateTimeField()),
                ('callsign', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.CallSign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True)),
                ('website', models.URLField(blank=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('callsign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='callsign.CallSign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transmitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('active', models.BooleanField(default=True)),
                ('transmit_frequency', models.FloatField()),
                ('offset', models.FloatField()),
                ('colorcode', models.SmallIntegerField(blank=True, null=True)),
                ('ctcss', models.FloatField(blank=True, choices=[(67.0, '67.0 Hz'), (69.3, '69.3 Hz'), (71.9, '71.9 Hz'), (74.4, '74.4 Hz'), (77.0, '77.0 Hz'), (79.7, '79.7 Hz'), (82.5, '82.5 Hz'), (85.4, '85.4 Hz'), (88.5, '88.5 Hz'), (91.5, '91.5 Hz'), (94.8, '94.8 Hz'), (97.4, '97.4 Hz'), (100.0, '100.0 Hz'), (103.5, '103.5 Hz'), (107.2, '107.2 Hz'), (110.9, '110.9 Hz'), (114.8, '114.8 Hz'), (118.8, '118.8 Hz'), (123.0, '123.0 Hz'), (127.3, '127.3 Hz'), (131.8, '131.8 Hz'), (136.5, '136.5 Hz'), (141.3, '141.3 Hz'), (146.2, '146.2 Hz'), (150.0, '150.0 Hz'), (151.4, '151.4 Hz'), (156.7, '156.7 Hz'), (159.8, '159.8 Hz'), (162.2, '162.2 Hz'), (165.5, '165.5 Hz'), (167.9, '167.9 Hz'), (171.3, '171.3 Hz'), (173.8, '173.8 Hz'), (177.3, '177.3 Hz'), (179.9, '179.9 Hz'), (183.5, '183.5 Hz'), (186.2, '186.2 Hz'), (189.9, '189.9 Hz'), (192.8, '192.8 Hz'), (196.6, '196.6 Hz'), (199.5, '199.5 Hz'), (203.5, '203.5 Hz'), (206.5, '206.5 Hz'), (210.7, '210.7 Hz'), (213.8, '213.8 Hz'), (218.1, '218.1 Hz'), (221.3, '221.3 Hz'), (225.7, '225.7 Hz'), (229.1, '229.1 Hz'), (233.6, '233.6 Hz'), (237.1, '237.1 Hz'), (241.8, '241.8 Hz'), (245.5, '245.5 Hz'), (250.3, '250.3 Hz'), (254.1, '254.1 Hz')], help_text='Continuous Tone Coded Squelch System', null=True, verbose_name='CTCSS')),
                ('mode', models.CharField(choices=[('am', 'AM'), ('fm', 'FM'), ('dstar', 'D-STAR'), ('dmr', 'DMR'), ('ssb', 'SSB')], max_length=16)),
                ('pep', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('echolink', models.IntegerField(blank=True, null=True)),
                ('repeater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmitters', to='callsign.Repeater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='callsignprefix',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='callsign.Country'),
        ),
        migrations.AddField(
            model_name='callsignprefix',
            name='dxcc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='callsign.DXCCEntry'),
        ),
        migrations.AddField(
            model_name='callsign',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='callsign.Country'),
        ),
        migrations.AddField(
            model_name='callsign',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsign',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callsign',
            name='prefix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='callsign.CallSignPrefix'),
        ),
        migrations.AlterUniqueTogether(
            name='dxccentry',
            unique_together={('name', 'deleted')},
        ),
    ]
