# Generated by Django 2.1 on 2018-12-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0004_prefix_import'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeater',
            name='website',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
