# Generated by Django 2.2 on 2019-04-24 11:36

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0006_dataimport_add_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transmitter',
            name='ctcss',
            field=models.DecimalField(blank=True, choices=[(Decimal('67.0'), '67.0 Hz'), (Decimal('69.3'), '69.3 Hz'), (Decimal('71.9'), '71.9 Hz'), (Decimal('74.4'), '74.4 Hz'), (Decimal('77.0'), '77.0 Hz'), (Decimal('79.7'), '79.7 Hz'), (Decimal('82.5'), '82.5 Hz'), (Decimal('85.4'), '85.4 Hz'), (Decimal('88.5'), '88.5 Hz'), (Decimal('91.5'), '91.5 Hz'), (Decimal('94.8'), '94.8 Hz'), (Decimal('97.4'), '97.4 Hz'), (Decimal('100.0'), '100.0 Hz'), (Decimal('103.5'), '103.5 Hz'), (Decimal('107.2'), '107.2 Hz'), (Decimal('110.9'), '110.9 Hz'), (Decimal('114.8'), '114.8 Hz'), (Decimal('118.8'), '118.8 Hz'), (Decimal('123.0'), '123.0 Hz'), (Decimal('127.3'), '127.3 Hz'), (Decimal('131.8'), '131.8 Hz'), (Decimal('136.5'), '136.5 Hz'), (Decimal('141.3'), '141.3 Hz'), (Decimal('146.2'), '146.2 Hz'), (Decimal('150.0'), '150.0 Hz'), (Decimal('151.4'), '151.4 Hz'), (Decimal('156.7'), '156.7 Hz'), (Decimal('159.8'), '159.8 Hz'), (Decimal('162.2'), '162.2 Hz'), (Decimal('165.5'), '165.5 Hz'), (Decimal('167.9'), '167.9 Hz'), (Decimal('171.3'), '171.3 Hz'), (Decimal('173.8'), '173.8 Hz'), (Decimal('177.3'), '177.3 Hz'), (Decimal('179.9'), '179.9 Hz'), (Decimal('183.5'), '183.5 Hz'), (Decimal('186.2'), '186.2 Hz'), (Decimal('189.9'), '189.9 Hz'), (Decimal('192.8'), '192.8 Hz'), (Decimal('196.6'), '196.6 Hz'), (Decimal('199.5'), '199.5 Hz'), (Decimal('203.5'), '203.5 Hz'), (Decimal('206.5'), '206.5 Hz'), (Decimal('210.7'), '210.7 Hz'), (Decimal('213.8'), '213.8 Hz'), (Decimal('218.1'), '218.1 Hz'), (Decimal('221.3'), '221.3 Hz'), (Decimal('225.7'), '225.7 Hz'), (Decimal('229.1'), '229.1 Hz'), (Decimal('233.6'), '233.6 Hz'), (Decimal('237.1'), '237.1 Hz'), (Decimal('241.8'), '241.8 Hz'), (Decimal('245.5'), '245.5 Hz'), (Decimal('250.3'), '250.3 Hz'), (Decimal('254.1'), '254.1 Hz')], decimal_places=1, help_text='Continuous Tone Coded Squelch System', max_digits=5, null=True, verbose_name='CTCSS'),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='pep',
            field=models.FloatField(blank=True, help_text='Peak Envelope Power in W', null=True, verbose_name='PEP'),
        ),
    ]
