# Generated by Django 2.2 on 2019-04-24 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0007_ctcss_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeater',
            name='callsign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.Callsign'),
        ),
    ]
