# Generated by Django 2.2 on 2019-04-25 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0008_repeater_onetoone'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataimport',
            name='duplicated_callsigns',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='club',
            name='callsign',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='callsign.Callsign'),
        ),
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
    ]
