# Generated by Django 2.2 on 2019-04-30 21:03

from django.conf import settings
from django.db import migrations, models
import project_novis.callsign.utils


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0009_club_onetoone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='owner',
        ),
        migrations.AlterField(
            model_name='callsign',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(project_novis.callsign.utils.get_sentinel_user), related_name='callsigns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='club',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(project_novis.callsign.utils.get_sentinel_user), related_name='clubs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='repeater',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(project_novis.callsign.utils.get_sentinel_user), related_name='repeaters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transmitter',
            name='created_by',
            field=models.ForeignKey(on_delete=models.SET(project_novis.callsign.utils.get_sentinel_user), related_name='transmitters', to=settings.AUTH_USER_MODEL),
        ),
    ]
