# Generated by Django 2.2 on 2019-05-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callsign', '0010_use_sentinel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to='callsign.Callsign'),
        ),
    ]
