from django.test import SimpleTestCase

from ..utils import extract_callsign


class ExtractCallsignTestCase(SimpleTestCase):
    def setUp(self):
        self.valid_callsigns = [
            "DO2FMW",
            "do2fmw",
            "IK4IDP",
            "HB9STEVE",
            "OEM6CLD",
            "A65BP"
        ]

        self.invalid_callsigns = [
            "208",
            "14642503",
            "aaaaaaaaaaaaaaa",
            "*****",
            "********",
            "*AMATEUR",
            "*TEST*",
            "0",
            "01",
            "1",
            "1INK",
            "1INK0",
            "1INK1",
            "2EOGSW",
            "2EOIQJ",
            "2EOMKV",
            "2EOSWT",
            "2E�FVL",
            "2E�GIO",
            "2E�XJR",
            "2MOLEW",
            "2SZ",
            "2WOSDO",
            "2YX",
            "2mocvk",
            "2mocvk/m",
            "2mocvk/p",
            "4KA",
            "5BAKVV",
            "6JRP",
            "74.91.12",
            "7OAGAA",
            "7QAA",
            "7QKW/1",
            "7QNL",
            "7QRO",
            "7QZZ",
            "9A/AFX",
            "9AIC",
            "9D8",
            "9LYXJ",
            "9LYXJ",
            "AAAAA",
            "ABCD8",
            "ACOBQ",
            "AKUSTIK",
            "ARMI",
            "ATMAN",
            "B-7",
            "BANGKALANG",
            "BANNED U",
            "BDAMS",
            "BGNYT",
            "BGTSI",
            "BILASIPARA",
            "BOLLATE",
            "BRUCE C",
            "BYLX",
            "CALL",
            "CALLSIG",
            "CAUHF Benton AR",
            "CH2",
            "CHAMPORCHER",
            "CHLINK",
            "CLTEST1",
            "CNTNA1",
            "CQCQCQ",
            "CQOXMAF",
            "CTJBB",
            "CUCURACHI",
            "DASODEV",
            "DAVID",
            "DAVUD",
            "DEVSIGN",
            "DF�LQ/P",
            "DIAZ",
            "DMR",
            "DMR Hamilton MT",
            "DMRBRIDG",
            "DMRGATE",
            "DMRPTL",
            "DMR_LINK",
            "DONDENA",
            "DRB",
            "DTDXA",
            "DTDXA 1",
            "DVSPTL",
            "DVSZLK",
            "Del Boca Vista",
            "EA4",
            "EA4-GKR",
            "EAGZD",
            "EAIR",
            "EAYY",
            "EBTT/P",
            "EILAT",
            "EKEH",
            "EWARN 2",
            "EWARN 3",
            "F",
            "FBDS",
            "FZMO",
            "GBOHE",
            "GB�TMT",
            "GILBOA",
            "GOJZW",
            "GRIPU",
            "GW Nordbaden - I,"
            "HAM",
            "HAMRADIO",
            "HI7-APW",
            "HOTSPOT",
            "HSPOT1",
            "I-99-NU",
            "I8-58/NA",
            "IDK",
            "ILDARIN",
            "INDICATI",
            "INFO",
            "IZ�KHE",
            "I�141RM",
            "I�ABU",
            "JGXUZ",
            "JIMMYTNT7",
            "JOE",
            "JRB",
            "K!FRA",
            "KB�OSC",
            "KDKA",
            "KDOBVI",
            "KF)C",
            "KHAKUN",
            "KIAVI",
            "KMPLS",
            "KOHU",
            "KORCJ",
            "KPEEC",
            "KQØRS",
            "KXXXXXY",
            "KØHTX",
            "LABOBO",
            "LAJFA",
            "LARC UHF DMR",
            "LINK",
            "LOCAL",
            "LOGS",
            "LPY",
            "LRPC-Morgan",
            "LTWLTW",
            "LUFKR",
            "LYC-2",
            "LYC-60",
            "LYC-60",
            "LZ2-K-81",
            "LiONA",
            "Loma Costa",
            "MASTER",
            "MATCOM1",
            "MATCOMS",
            "MMDVM",
            "MODIIN",
            "MOHFC",
            "MOJLS",
            "MOLSG",
            "MOO",
            "MORCX",
            "MUSEO_ALFA_ROMEO",
            "MWODSV",
            "MWOKMS",
            "MWoZAK/p",
            "MYCALL",
            "Mah VHF BM test",
            "Manara",
            "Mizpe Ramon",
            "Motorola",
            "Mototrbo",
            "My Radio",
            "NCAARS",
            "NO CAL",
            "NOCALD",
            "NOCALL",
            "NONE",
            "NONFB",
            "North Park",
            "NØVPR Baxter",
            "N�U",
            "N�YH",
            "OE1",
            "OKBPA",
            "OPENSPOT",
            "ORIGGIO",
            "OTTONE",
            "OWNCALL",
            "PALLARS",
            "PARROT",
            "PA�PSY",
            "PDF",
            "PEPELOZ5",
            "PIET",
            "PIPPO",
            "PIRATE",
            "PISTAR",
            "PLBRIDGE",
            "PU2",
            "PU4-UGO",
            "PYC MAST A",
            "Pigeon Forge",
            "QRM-CHAT",
            "RADIO1",
            "RADIOAF",
            "RAEM",
            "RC cordillera",
            "RDM",
            "REACT NM Primary,"
            "REFL",
            "RMHR-LeeHill BM",
            "RMZO",
            "ROOT",
            "RussNet DMR",
            "SABSK",
            "SAN_BARTELEMY",
            "SERVTEC",
            "SHMA",
            "SIXDG1",
            "SMOZEY",
            "SOWELUYY",
            "SP",
            "SQ9",
            "SQNESIE",
            "SQVLADO",
            "SV2/SVINJW/P",
            "SWL",
            "SWLJRB",
            "SWLR-AN��9",
            "SWL_VK1",
            "Steinbruch Leubs,"
            "TEMP",
            "TEST",
            "TESTING",
            "TESTRPT",
            "TEXAS",
            "TJ",
            "TRAFFX",
            "TRSTRBO",
            "TX9",
            "UROEUC",
            "US-E-12",
            "US-E-12",
            "US-N-55",
            "US-W-43",
            "US-W-43",
            "VE2-HWD",
            "VE7-BPS",
            "VICTOR",
            "VK---",
            "VK1",
            "VK2***",
            "VLFBOY",
            "W2-01",
            "W2-01",
            "WD4",
            "WEAR",
            "WESTCREEK",
            "WOODBURY",
            "Williamston",
            "W�CHH",
            "W�KH",
            "W�VET",
            "XF!AA",
            "XXXX",
            "XXXXX",
            "XXXXXXX",
            "YB8/P_MANADOTUA",
            "YL-RS-01",
            "YL-RS-01",
            "YL-RS-33",
            "YV3-SWL",
            "ZWA",
        ]

        self.extract_callsings = [
            ("wd1s/vy2", "WD1S"),
            ("zl/pa0mir", "PA0MIR"),
            ("YV5/UA9YPS", "UA9YPS"),
            ("YV4KW/QRP", "YV4KW"),
            ("YO5DSG-M", "YO5DSG"),
            ("3A/DL6KR/P", "DL6KR"),
            ("AC8JF/P-ADRIAN", "AC8JF"),
            ("AE5DN-Stillwater", "AE5DN"),
            ("AH6OO - Honolulu", "AH6OO"),
            ("BA4TB/5_DAYANG", "BA4TB"),
            ("CT3/CT1BWU/P", "CT1BWU"),
            ("DU1/EA3NT_OC128", "EA3NT"),
            ("EA6/DL5DCL_2007", "DL5DCL"),
            ("HB0/DL9MDI/p", "DL9MDI"),
            ("DL/K3ZFP/3", "K3ZFP"),
            ("K3ZFP/3", "K3ZFP"),
        ]

    def test_invalid_callsings(self):
        for i in self.invalid_callsigns:
            with self.subTest(i=i):
                self.assertEqual(extract_callsign(i), "")

    def test_valid_callsings(self):
        for i in self.valid_callsigns:
            with self.subTest(i=i):
                self.assertEqual(extract_callsign(i), i.upper())

    def test_extract_callsign(self):
        for i in self.extract_callsings:
            with self.subTest(i=i):
                self.assertEqual(extract_callsign(i[0]), i[1])
