# Generated by Django 2.1b1 on 2018-06-25 13:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('secret', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('wifi', 'WiFi'), ('switch', 'Switch'), ('vpn', 'VPN'), ('other', 'Other')], max_length=32)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_request', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='Modified')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
